<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-N7K85DJ" name="AUW_Firefox_Prod" tests="10" failures="1" timestamp="9 May 2022 10:02:35 GMT" time="1085.848" errors="0">
  <testcase name="AUW_Footer" time="72.403" classname="AUW_Test_case_prod.AUW_Footer_Prod"/>
  <testcase name="AboutUS" time="70.311" classname="AUW_Test_case_prod.AUW_AboutUS"/>
  <testcase name="main" time="16.844" classname="AUW_Test_case_prod.AUW_PPP"/>
  <testcase name="main" time="22.063" classname="AUW_Test_case_prod.AUW_NJ_Update">
    <failure type="java.lang.AssertionError" message="expected [https://www.auw.com/njupdate/auw-challenge-court-ruling-new-jersey-department-of-banking-insurance-nju] but found [https://www.auw.com/njupdate]">
      <![CDATA[java.lang.AssertionError: expected [https://www.auw.com/njupdate/auw-challenge-court-ruling-new-jersey-department-of-banking-insurance-nju] but found [https://www.auw.com/njupdate]
	at AUW_Pages.NJ_Update.Facts_View(NJ_Update.java:88)
	at AUW_Test_case_prod.AUW_NJ_Update.main(AUW_NJ_Update.java:18)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- main -->
  <testcase name="main" time="38.272" classname="AUW_Test_case_prod.AUW_CallUpdate"/>
  <testcase name="main" time="333.03" classname="AUW_Test_case_prod.AUW_Experience"/>
  <testcase name="main" time="78.818" classname="AUW_Test_case_prod.AUW_Intelligence_TC"/>
  <testcase name="main" time="48.17" classname="AUW_Test_case_prod.AUW_header_web_Prod"/>
  <testcase name="Practices_AgentsBrokers" time="53.693" classname="AUW_Test_case_prod.Practices_AgentsBrokers"/>
  <testcase name="Practices_CustomerSeekingCoverage" time="249.81" classname="AUW_Test_case_prod.Practices_CustomerSeekingCoverage"/>
</testsuite> <!-- AUW_Firefox_Prod -->
